.TH rssreader 1 "2011-02-26"
.LO 1
.SH NAME
rssreader \- command line, curses based, rss reader
.SH SYNOPSIS
rssreader [FILE]
.SH DESCRIPTION
.I rssreader
is a feed and atom reader with 
.I vi 
like navigation in mind. It also borrows some of its functionality from
.IR screen .
The most common usage is "rssreader" or "rssreader filename".
.SH FILES
rssreader reads the feeds from a config file.
.PP
If not given in the command line it defaults to
.BI $HOME/.rssreaderrc
.SH SEE ALSO
.B rssreaderrc(5)
.SH AUTHOR
Author of rssreader is Dustin Koupal and Norberto Lopes. 
.SH BUGS
Send them to dustink@gmail.com or nlopes.ml@gmail.com.
